apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: amq-broker-76-persistence
  xpaas: 1.4.16
message: A new messaging service has been created in your project. It will handle
  the protocol(s) "${AMQ_PROTOCOL}". The username/password for accessing the service
  is ${AMQ_USER}/${AMQ_PASSWORD}.
metadata:
  annotations:
    description: Application template for Red Hat AMQ brokers. This template doesn't
      feature SSL support.
    iconClass: icon-amq
    openshift.io/display-name: Red Hat AMQ Broker 7.6 (Persistence, no SSL)
    openshift.io/provider-display-name: Red Hat, Inc.
    tags: messaging,amq,xpaas
    template.openshift.io/documentation-url: https://access.redhat.com/documentation/en/red-hat-amq/
    template.openshift.io/long-description: This template defines resources needed
      to develop a Red Hat AMQ Broker 7.6 based application, including a statefulset
      configuration, using persistent storage.
    template.openshift.io/support-url: https://access.redhat.com
    version: 1.4.16
  creationTimestamp: 2020-05-13T13:13:17Z
  name: amq-broker-76-persistence
  namespace: malware-nextgen-lcurry-staging
  resourceVersion: "8137385"
  selfLink: /apis/template.openshift.io/v1/namespaces/malware-nextgen-lcurry-staging/templates/amq-broker-76-persistence
  uid: 827b5c30-951b-11ea-88f5-06580a32acee
objects:
- apiVersion: v1
  data:
    ${AMQ_PASSWORD}: YWRtaW4=
    ${AMQ_USER}: YWRtaW4=
  kind: Secret
  metadata:
    annotations:
      description: Credentials used in broker config. Default values are admin(AMQ_USER
        and AMQ_PASSWORD).
    name: amq-credential-secret
  type: Opaque
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The broker's headless, non load balanced service
    labels:
      app: ${APPLICATION_NAME}
      application: ${APPLICATION_NAME}
    name: ${AMQ_NAME}-amq-headless
  spec:
    clusterIP: None
    ports:
    - name: all
      port: 61616
      protocol: TCP
      targetPort: 61616
    - name: console-jolokia
      port: 8161
      protocol: TCP
      targetPort: 8161
    - name: amqp
      port: 5672
      protocol: TCP
      targetPort: 5672
    - name: mqtt
      port: 1883
      protocol: TCP
      targetPort: 1883
    - name: stomp
      port: 61613
      protocol: TCP
      targetPort: 61613
    publishNotReadyAddresses: true
    selector:
      deploymentConfig: ${APPLICATION_NAME}-amq
    type: ClusterIP
- apiVersion: apps/v1beta1
  kind: StatefulSet
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-amq
  spec:
    podManagementPolicy: OrderedReady
    selector:
      matchLabels:
        app: ${APPLICATION_NAME}-amq
    serviceName: ${AMQ_NAME}-amq-headless
    strategy:
      rollingParams:
        maxSurge: 0
      type: Rolling
    template:
      metadata:
        labels:
          app: ${APPLICATION_NAME}-amq
          application: ${APPLICATION_NAME}
          deploymentConfig: ${APPLICATION_NAME}-amq
        name: ${APPLICATION_NAME}-amq
      spec:
        containers:
        - env:
          - name: AMQ_USER
            valueFrom:
              secretKeyRef:
                key: ${AMQ_USER}
                name: ${AMQ_CREDENTIAL_SECRET}
          - name: AMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                key: ${AMQ_PASSWORD}
                name: ${AMQ_CREDENTIAL_SECRET}
          - name: AMQ_ROLE
            value: ${AMQ_ROLE}
          - name: AMQ_NAME
            value: ${AMQ_NAME}
          - name: AMQ_TRANSPORTS
            value: ${AMQ_PROTOCOL}
          - name: AMQ_QUEUES
            value: ${AMQ_QUEUES}
          - name: AMQ_ADDRESSES
            value: ${AMQ_ADDRESSES}
          - name: AMQ_GLOBAL_MAX_SIZE
            value: ${AMQ_GLOBAL_MAX_SIZE}
          - name: AMQ_REQUIRE_LOGIN
            value: ${AMQ_REQUIRE_LOGIN}
          - name: AMQ_DATA_DIR
            value: ${AMQ_DATA_DIR}
          - name: AMQ_DATA_DIR_LOGGING
            value: ${AMQ_DATA_DIR_LOGGING}
          - name: AMQ_EXTRA_ARGS
            value: ${AMQ_EXTRA_ARGS}
          - name: AMQ_ANYCAST_PREFIX
            value: ${AMQ_ANYCAST_PREFIX}
          - name: AMQ_MULTICAST_PREFIX
            value: ${AMQ_MULTICAST_PREFIX}
          - name: AMQ_ENABLE_METRICS_PLUGIN
            value: ${AMQ_ENABLE_METRICS_PLUGIN}
          - name: AMQ_JOURNAL_TYPE
            value: ${AMQ_JOURNAL_TYPE}
          image: ${IMAGE}
          name: ${APPLICATION_NAME}-amq
          ports:
          - containerPort: 8161
            name: console-jolokia
            protocol: TCP
          - containerPort: 5672
            name: amqp
            protocol: TCP
          - containerPort: 1883
            name: mqtt
            protocol: TCP
          - containerPort: 61613
            name: stomp
            protocol: TCP
          - containerPort: 61616
            name: all
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - /opt/amq/bin/readinessProbe.sh
          volumeMounts:
          - mountPath: ${AMQ_DATA_DIR}
            name: ${APPLICATION_NAME}-amq-pvol
        terminationGracePeriodSeconds: 60
        imagePullSecrets:
        - name: ${IMAGE_PULL_SECRET}
    triggers:
    - type: ConfigChange
    volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: ${APPLICATION_NAME}-amq-pvol
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: ${VOLUME_CAPACITY}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${APPLICATION_NAME}
      application: ${APPLICATION_NAME}
    name: console-jolokia
  spec:
    port:
      targetPort: console-jolokia
    to:
      kind: Service
      name: ${AMQ_NAME}-amq-headless
parameters:
- description: The name for the application.
  displayName: Application Name
  name: APPLICATION_NAME
  required: true
  value: broker
- description: 'Protocols to configure, separated by commas. Allowed values are: `openwire`,
    `amqp`, `stomp`, `mqtt` and `hornetq`.'
  displayName: AMQ Protocols
  name: AMQ_PROTOCOL
  value: openwire,amqp,stomp,mqtt,hornetq
- description: Queue names, separated by commas. These queues will be automatically
    created when the broker starts. If left empty, queues will be still created dynamically.
  displayName: Queues
  name: AMQ_QUEUES
- description: Address names, separated by commas. These addresses will be automatically
    created when the broker starts. If left empty, addresses will be still created
    dynamically.
  displayName: Addresses
  name: AMQ_ADDRESSES
- description: Size of the volume used by AMQ for persisting messages.
  displayName: AMQ Volume Size
  name: VOLUME_CAPACITY
  required: true
  value: 1Gi
- description: User name for standard broker user. It is required for connecting to
    the broker. If left empty, it will be generated. It serves as a key by which the
    real user name is retrieved from kubernetes secret object.
  displayName: AMQ Username
  from: user[a-zA-Z0-9]{3}
  generate: expression
  name: AMQ_USER
- description: Password for standard broker user. It is required for connecting to
    the broker. If left empty, it will be generated. It serves as a key by which the
    real password is retrieved from kubernetes secret object.
  displayName: AMQ Password
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: AMQ_PASSWORD
- description: User role for standard broker user.
  displayName: AMQ Role
  name: AMQ_ROLE
  value: admin
- description: The name of the broker
  displayName: AMQ Name
  name: AMQ_NAME
  value: broker
- description: The directory to use for data storage
  displayName: AMQ Data Directory
  name: AMQ_DATA_DIR
  value: /opt/amq/data
- description: Use the AMQ Data Directory for logging
  displayName: AMQ Data Directory for logging
  name: AMQ_DATA_DIR_LOGGING
  value: "true"
- description: 'Maximum amount of memory which message data may consume (Default:
    Undefined, half of the system''s memory).'
  displayName: AMQ Global Max Size
  name: AMQ_GLOBAL_MAX_SIZE
  value: 100 gb
- description: Determines whether or not the broker will allow anonymous access, or
    require login.
  displayName: AMQ Require Login
  name: AMQ_REQUIRE_LOGIN
- description: Extra arguments for broker creation
  name: AMQ_EXTRA_ARGS
- description: Anycast prefix applied to the multiplexed protocol port 61616
  displayName: AMQ Anycast Prefix
  name: AMQ_ANYCAST_PREFIX
- description: Multicast prefix applied to the multiplexed protocol port 61616
  displayName: AMQ Multicast Prefix
  name: AMQ_MULTICAST_PREFIX
- description: Broker Image
  displayName: Image
  name: IMAGE
  required: true
  value: registry.redhat.io/amq7/amq-broker:7.6
- description: Name of a secret containing credential data such as usernames and passwords
  displayName: Secret Name
  name: AMQ_CREDENTIAL_SECRET
  required: true
  value: amq-credential-secret
- description: Whether to enable artemis metrics plugin
  displayName: Enable Metrics Plugin
  name: AMQ_ENABLE_METRICS_PLUGIN
  value: "false"
- description: Journal type to use; aio or nio supported
  displayName: AMQ Journal Type
  name: AMQ_JOURNAL_TYPE
  value: nio
- description: Image pull secret
  displayName: Name of Image pull secret
  name: IMAGE_PULL_SECRET
  value: artifactory-puller