---
apiVersion: v1
kind: Template
metadata:
  name: route-template
objects:
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${SERVICE}
      application: ${SERVICE}
    name: console-jolokia
  spec:
    port:
      targetPort: console-jolokia
    to:
      kind: Service
      name: ${AMQ_NAME}-amq-headless    
parameters:
  - name: SERVICE
    displayName: Service Name
    description: Service Name
    required: true
  - description: The name of the broker
    displayName: AMQ Name
    name: AMQ_NAME
    value: broker
